# Generated by Django 2.2.3 on 2019-08-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20190805_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarInfo',
            fields=[
                ('star_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('e_name', models.CharField(max_length=200)),
                ('star_type', models.CharField(max_length=50)),
                ('star_other', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reels', models.CharField(max_length=1000)),
                ('sex', models.IntegerField(default=0)),
            ],
        ),
    ]
